{% set data = load_setup_py_data() %}

package:
  name: emat
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python>=3.7
  host:
    - python>=3.7
    - numpy>=1.15
    - pandas>=0.24
    - appdirs>=1.4
    - pydot>=1.3
    - plotly>=3.4.2
    - scipy>=1.2
    - seaborn>=0.9.0
    - pyyaml>=5.1
    - tmip::ema_workbench
  run:
    - python>=3.7
    - numpy>=1.15
    - pandas>=0.24
    - appdirs>=1.4
    - pydot>=1.3
    - plotly>=3.4.2
    - scipy>=1.2
    - seaborn>=0.9.0
    - pyyaml>=5.1
    - tmip::ema_workbench

test:
  # Python imports
  imports:
    - emat

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  license: MIT
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
